version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      -  61014:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
